package com.trafficsimulator.service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

import com.fasterxml.jackson.databind.JsonNode;
import com.trafficsimulator.config.MapConfig;
import com.trafficsimulator.dto.BboxRequest;

/**
 * Translates an osm2streets {@code StreetNetwork} JSON tree into a {@link MapConfig} suitable for
 * loading into the simulation engine. Phase 24 Plan 24-04.
 *
 * <p>Input contract (Plan 24-01 SUMMARY "Observed StreetNetwork JSON Shape"):
 * <ul>
 *   <li>Top-level: {@code roads} and {@code intersections} as tuple-arrays ({@code [[id, value], ...]}).
 *   <li>LaneSpec fields: {@code lt} (bare string OR tagged {@code {VariantName: payload}} object),
 *       {@code dir} ({@code Forward} / {@code Backward} / {@code Both}), {@code width} (flat i32
 *       scaled × 10 000 — 30000 = 3.0 m).
 *   <li>{@code Road.reference_line.length} is i32 scaled → metres.
 *   <li>{@code Road.speed_limit} is nullable i32 scaled → m/s.
 *   <li>Intersection {@code kind}: {@code Terminus} / {@code MapEdge} / {@code Connection} /
 *       {@code Fork} / {@code Intersection}. {@code control}: {@code Uncontrolled} /
 *       {@code Signed} / {@code Signalled} / {@code Construction}.
 *   <li>{@code gps_bounds} carries {@code min_lon/min_lat/max_lon/max_lat} used to reverse-project
 *       the internal {x,y} coordinates (scaled metres from the NW corner) back to lon/lat. The
 *       caller's {@link BboxRequest} then projects those onto the MapConfig canvas via
 *       {@link OsmConversionUtils#lonToX(double, double, double)} + {@link OsmConversionUtils#latToY(double, double, double)}.
 * </ul>
 *
 * <p>Output contract:
 * <ul>
 *   <li>All node / road ids prefixed {@code o2s-} so A/B/C comparison outputs can be interleaved
 *       without collision with {@code osm-} (Phase 18) or {@code gh-} (Phase 23).
 *   <li>{@code RoadConfig.laneCount} = count of {@code Driving} lanes in the osm2streets road,
 *       clamped to {@link OsmConversionUtils#MAX_LANE_COUNT}. Falls back to 1 if no driving lanes.
 *   <li>{@code RoadConfig.lanes} populated from the MVP-filtered LaneSpec list (driving / parking
 *       / cycling / sidewalk only — Shoulder, Buffer, Bus, etc. dropped per 24-CONTEXT §7).
 *   <li>Intersections with {@code control == "Signalled"} become {@code SIGNAL} IntersectionConfigs
 *       with signal phases generated by {@link OsmConversionUtils#buildDefaultSignalPhases}.
 *       Every other control maps to {@code PRIORITY} — the documented roundabout-detection gap
 *       (RESEARCH Pitfall 5) is accepted for MVP.
 *   <li>Terminal intersections ({@code kind} == {@code Terminus} or {@code MapEdge}) become
 *       ENTRY/EXIT {@link MapConfig.NodeConfig}s with spawn / despawn points attached via
 *       {@link OsmConversionUtils#collectSpawnPoints} / {@link OsmConversionUtils#collectDespawnPoints}.
 * </ul>
 *
 * <p>Empty inputs (zero roads after filtering) throw {@link IllegalStateException} with
 * "No roads found in selected area" — the caller ({@link Osm2StreetsService#fetchAndConvert})
 * maps this to HTTP 422.
 */
final class StreetNetworkMapper {

    /** ID prefix on every node + road emitted by this mapper (A/B/C comparison tag). */
    static final String ID_PREFIX = "o2s-";

    /** Default lane width fallback when the LaneSpec carries no usable width (metres). */
    private static final double DEFAULT_LANE_WIDTH_M = 3.5;

    /** Scale factor used by osm2streets for f64 metres → i32 wire-format (Plan 24-01 SUMMARY "Geom scaling"). */
    private static final double GEOM_SCALE = 10_000.0;

    /** MVP lane types accepted in {@code RoadConfig.lanes}. Every other type is dropped. */
    private static final Set<String> MVP_LANE_TYPES =
            Set.of("driving", "parking", "cycling", "sidewalk");

    /** Map from osm2streets LaneType tag name → MapConfig MVP type label. */
    private static final Map<String, String> LANE_TYPE_TO_MVP = Map.of(
            "Driving", "driving",
            "Parking", "parking",
            "Biking", "cycling",
            "Sidewalk", "sidewalk");

    /** osm2streets IntersectionControl value that maps to {@code SIGNAL}. */
    private static final String SIGNALLED_CONTROL = "Signalled";

    /** Intersection kinds that represent map-boundary terminals (ENTRY/EXIT in our schema). */
    private static final Set<String> TERMINAL_KINDS = Set.of("Terminus", "MapEdge");

    private StreetNetworkMapper() {
        // utility class
    }

    /** Intermediate record for a parsed osm2streets road. */
    private record ParsedRoad(
            int id,
            int srcI,
            int dstI,
            String highway,
            double lengthM,
            Double speedLimitMps,
            int drivingCount,
            List<MapConfig.LaneConfig> mvpLanes) {}

    /** Intermediate record for a parsed osm2streets intersection. */
    private record ParsedIntersection(
            int id, String kind, String control, double avgX, double avgY) {}

    /**
     * Entry point. Converts the given StreetNetwork JSON tree to a MapConfig.
     *
     * @throws IllegalStateException if the input contains no roads after MVP filtering
     */
    static MapConfig map(JsonNode network, BboxRequest bbox) {
        JsonNode gpsBounds = network.path("gps_bounds");
        double minLon = gpsBounds.path("min_lon").asDouble();
        double minLat = gpsBounds.path("min_lat").asDouble();
        double maxLon = gpsBounds.path("max_lon").asDouble();
        double maxLat = gpsBounds.path("max_lat").asDouble();

        List<ParsedRoad> parsedRoads = parseRoads(network.path("roads"));
        if (parsedRoads.isEmpty()) {
            throw new IllegalStateException("No roads found in selected area");
        }

        Map<Integer, ParsedIntersection> parsedIntersections =
                parseIntersections(network.path("intersections"));

        // Build MapConfig.RoadConfig list from parsed roads. Each osm2streets road becomes a single
        // directed RoadConfig (src_i -> dst_i); bidirectional richness is preserved in the lanes[]
        // list via per-lane direction metadata.
        List<MapConfig.RoadConfig> roads = new ArrayList<>();
        for (ParsedRoad pr : parsedRoads) {
            String fromId = ID_PREFIX + pr.srcI();
            String toId = ID_PREFIX + pr.dstI();
            double speedLimit = pr.speedLimitMps() != null
                    ? pr.speedLimitMps()
                    : OsmConversionUtils.speedLimitForHighway(pr.highway());
            double length = Math.max(OsmConversionUtils.MIN_ROAD_LENGTH_M, pr.lengthM());
            int laneCount = Math.max(OsmConversionUtils.MIN_LANE_COUNT,
                    Math.min(OsmConversionUtils.MAX_LANE_COUNT, Math.max(1, pr.drivingCount())));

            MapConfig.RoadConfig rc = OsmConversionUtils.buildRoadConfig(
                    ID_PREFIX + pr.id(), fromId, toId, length, speedLimit, laneCount, 0.0);
            if (!pr.mvpLanes().isEmpty()) {
                rc.setLanes(pr.mvpLanes());
            }
            roads.add(rc);
        }

        // Orphan filter — only emit NodeConfigs for intersections that actually terminate a road.
        Set<Integer> usedIntersectionIds = new HashSet<>();
        for (ParsedRoad pr : parsedRoads) {
            usedIntersectionIds.add(pr.srcI());
            usedIntersectionIds.add(pr.dstI());
        }

        // Build NodeConfig list. Classification:
        //   - Terminal kind (Terminus / MapEdge): ENTRY if used as src, EXIT if only as dst, else ENTRY.
        //   - Non-terminal kind (Connection / Fork / Intersection): INTERSECTION.
        Set<Integer> srcIds = new HashSet<>();
        Set<Integer> dstIds = new HashSet<>();
        for (ParsedRoad pr : parsedRoads) {
            srcIds.add(pr.srcI());
            dstIds.add(pr.dstI());
        }

        List<MapConfig.NodeConfig> nodes = new ArrayList<>();
        List<MapConfig.IntersectionConfig> intersections = new ArrayList<>();
        for (Map.Entry<Integer, ParsedIntersection> e : parsedIntersections.entrySet()) {
            int id = e.getKey();
            if (!usedIntersectionIds.contains(id)) {
                continue;
            }
            ParsedIntersection pi = e.getValue();
            String fullId = ID_PREFIX + id;
            MapConfig.NodeConfig nc = new MapConfig.NodeConfig();
            nc.setId(fullId);

            double[] lonLat = internalPointToLonLat(pi.avgX(), pi.avgY(), minLon, minLat, maxLon, maxLat);
            nc.setX(OsmConversionUtils.lonToX(lonLat[0], bbox.west(), bbox.east()));
            nc.setY(OsmConversionUtils.latToY(lonLat[1], bbox.south(), bbox.north()));

            if (TERMINAL_KINDS.contains(pi.kind())) {
                boolean isSrc = srcIds.contains(id);
                boolean isDst = dstIds.contains(id);
                if (isSrc && !isDst) {
                    nc.setType("ENTRY");
                } else if (isDst && !isSrc) {
                    nc.setType("EXIT");
                } else {
                    // Bidirectional terminal — classify as ENTRY (matches Phase 18/23 precedent
                    // for bidirectional-way endpoints).
                    nc.setType("ENTRY");
                }
            } else {
                nc.setType("INTERSECTION");
                MapConfig.IntersectionConfig ic = new MapConfig.IntersectionConfig();
                ic.setNodeId(fullId);
                if (SIGNALLED_CONTROL.equals(pi.control())) {
                    ic.setType("SIGNAL");
                    ic.setSignalPhases(OsmConversionUtils.buildDefaultSignalPhases(fullId, roads));
                } else {
                    // Roundabout-detection gap (RESEARCH Pitfall 5): osm2streets does not forward
                    // the OSM junction=roundabout tag to a distinct control value; every
                    // non-Signalled control collapses to PRIORITY for MVP.
                    ic.setType("PRIORITY");
                }
                intersections.add(ic);
            }
            nodes.add(nc);
        }

        // Spawn / despawn points — driven by terminal nodes.
        List<MapConfig.SpawnPointConfig> spawnPoints = new ArrayList<>();
        List<MapConfig.DespawnPointConfig> despawnPoints = new ArrayList<>();
        for (MapConfig.NodeConfig n : nodes) {
            if ("ENTRY".equals(n.getType())) {
                OsmConversionUtils.collectSpawnPoints(n.getId(), roads, spawnPoints);
            }
            if ("EXIT".equals(n.getType())) {
                OsmConversionUtils.collectDespawnPoints(n.getId(), roads, despawnPoints);
            }
        }

        return OsmConversionUtils.assembleMapConfig(
                bbox, nodes, roads, intersections, spawnPoints, despawnPoints);
    }

    // ------------------------------------------------------------------------
    // Parsing helpers
    // ------------------------------------------------------------------------

    private static List<ParsedRoad> parseRoads(JsonNode roadsArray) {
        List<ParsedRoad> out = new ArrayList<>();
        if (!roadsArray.isArray()) {
            return out;
        }
        for (JsonNode tuple : roadsArray) {
            if (!tuple.isArray() || tuple.size() < 2) {
                continue;
            }
            int id = tuple.get(0).asInt();
            JsonNode road = tuple.get(1);
            int srcI = road.path("src_i").asInt();
            int dstI = road.path("dst_i").asInt();
            String highway = road.path("highway_type").asText("residential");

            JsonNode refLine = road.path("reference_line");
            double lengthM = refLine.path("length").asDouble(0.0) / GEOM_SCALE;

            Double speedLimit = null;
            JsonNode sl = road.path("speed_limit");
            if (sl.isNumber()) {
                speedLimit = sl.asDouble() / GEOM_SCALE;
            }

            LaneExtraction lx = extractLanes(road.path("lane_specs_ltr"));

            out.add(new ParsedRoad(id, srcI, dstI, highway, lengthM, speedLimit,
                    lx.drivingCount, lx.mvpLanes));
        }
        return out;
    }

    private static Map<Integer, ParsedIntersection> parseIntersections(JsonNode intersectionsArray) {
        Map<Integer, ParsedIntersection> out = new LinkedHashMap<>();
        if (!intersectionsArray.isArray()) {
            return out;
        }
        for (JsonNode tuple : intersectionsArray) {
            if (!tuple.isArray() || tuple.size() < 2) {
                continue;
            }
            int id = tuple.get(0).asInt();
            JsonNode intersection = tuple.get(1);
            String kind = intersection.path("kind").asText("Intersection");
            String control = intersection.path("control").asText("Signed");

            double[] centroid = polygonCentroid(intersection.path("polygon"));
            out.put(id, new ParsedIntersection(id, kind, control, centroid[0], centroid[1]));
        }
        return out;
    }

    /** Result of MVP-filtering + driving-count of a single road's lane_specs_ltr. */
    private record LaneExtraction(int drivingCount, List<MapConfig.LaneConfig> mvpLanes) {}

    private static LaneExtraction extractLanes(JsonNode laneSpecsLtr) {
        List<MapConfig.LaneConfig> mvp = new ArrayList<>();
        int drivingCount = 0;
        if (!laneSpecsLtr.isArray()) {
            return new LaneExtraction(0, mvp);
        }
        for (JsonNode ls : laneSpecsLtr) {
            String rawType = extractLaneType(ls.path("lt"));
            String mvpType = LANE_TYPE_TO_MVP.get(rawType);
            if (mvpType == null || !MVP_LANE_TYPES.contains(mvpType)) {
                // Non-MVP (Shoulder, Buffer, Bus, SharedLeftTurn, Construction, LightRail, Footway)
                // dropped per 24-CONTEXT §7.
                continue;
            }
            if ("driving".equals(mvpType)) {
                drivingCount++;
            }
            double widthM = parseWidthMeters(ls.path("width"));
            String direction = normalizeDirection(ls.path("dir").asText("Forward"));
            mvp.add(new MapConfig.LaneConfig(mvpType, widthM, direction));
        }
        return new LaneExtraction(drivingCount, mvp);
    }

    /**
     * Extracts the tag name from a LaneType JSON value. Handles both plain strings (e.g.
     * {@code "Driving"}) and single-key tagged objects (e.g. {@code {"Parking": "Parallel"}}).
     */
    private static String extractLaneType(JsonNode lt) {
        if (lt.isTextual()) {
            return lt.asText();
        }
        if (lt.isObject() && lt.fieldNames().hasNext()) {
            Iterator<String> it = lt.fieldNames();
            return it.next();
        }
        return "";
    }

    /**
     * Reads the LaneSpec {@code width} field. Handles the observed flat-i32 shape
     * ({@code "width": 30000}) and, defensively per the plan's Q3 MEDIUM-confidence note, a nested
     * {@code {"inner": ...}} wrapper shape as fallback. Both are divided by {@link #GEOM_SCALE}
     * to produce metres; falls back to {@link #DEFAULT_LANE_WIDTH_M} when nothing usable is found.
     */
    private static double parseWidthMeters(JsonNode width) {
        if (width.isNumber()) {
            return width.asDouble() / GEOM_SCALE;
        }
        if (width.isObject()) {
            JsonNode inner = width.path("inner");
            if (inner.isNumber()) {
                return inner.asDouble() / GEOM_SCALE;
            }
        }
        return DEFAULT_LANE_WIDTH_M;
    }

    /**
     * Normalises osm2streets Direction strings to our {@code forward/backward/both} lowercase
     * vocabulary (matches {@link MapConfig.LaneConfig#getDirection()} contract).
     */
    private static String normalizeDirection(String raw) {
        String v = raw == null ? "" : raw.trim();
        return switch (v) {
            case "Forward" -> "forward";
            case "Backward" -> "backward";
            case "Both" -> "both";
            default -> v.toLowerCase(Locale.ROOT);
        };
    }

    /**
     * Centroid of a polygon serialised as {@code {"rings":[{"pts":[{"x":…,"y":…},…]}]}}.
     * Simple arithmetic mean of all pts across every ring; sufficient for node placement.
     * Returns {@code {0.0, 0.0}} for empty / missing polygons (caller uses gps_bounds origin).
     */
    private static double[] polygonCentroid(JsonNode polygon) {
        double sumX = 0.0;
        double sumY = 0.0;
        int count = 0;
        JsonNode rings = polygon.path("rings");
        if (rings.isArray()) {
            for (JsonNode ring : rings) {
                JsonNode pts = ring.path("pts");
                if (!pts.isArray()) {
                    continue;
                }
                for (JsonNode p : pts) {
                    sumX += p.path("x").asDouble(0.0);
                    sumY += p.path("y").asDouble(0.0);
                    count++;
                }
            }
        }
        if (count == 0) {
            return new double[] {0.0, 0.0};
        }
        return new double[] {sumX / count, sumY / count};
    }

    /**
     * Reverse-projects an internal (x, y) pair — scaled metres from the NW corner of
     * {@code gps_bounds} — back to (lon, lat). The NW corner is {@code (min_lon, max_lat)}.
     *
     * <p>Uses a flat-Earth approximation adequate for the small bboxes we care about (city-block
     * scale, < 1 km). {@code lon_span_m = cos(mid_lat) × lat_span_m × (lon_span_deg / lat_span_deg)}
     * but we only need the inverse of the x/y scaling osm2streets applied — which is itself a flat
     * approximation — so reversing with the same ratio is consistent.
     */
    private static double[] internalPointToLonLat(
            double x, double y, double minLon, double minLat, double maxLon, double maxLat) {
        // osm2streets scales its internal coordinates so that max_x corresponds to max_lon and
        // max_y corresponds to min_lat (Y axis flipped — north = y=0). We therefore invert the
        // ratio against the internal extent; internal extent equals the gps-bounds lon/lat span
        // × some fixed metres-per-degree factor, so the ratios cancel and we get a direct mapping
        // from (x, y) to (lon, lat) that is correct to within the same flat-Earth error osm2streets
        // applies itself.
        //
        // Build a proxy reference by inspecting the straight fixture (Plan 24-01 SUMMARY): for
        // gps_bounds span 0.001° × 0.001°, the internal extent is {x: 681215, y: 1111949}. So
        // internal_x_per_deg_lon ≈ 681 215 / 0.001 ≈ 6.81e8 (meters × 10 000) × cos(52.22°);
        // internal_y_per_deg_lat ≈ 1 111 949 / 0.001 ≈ 1.11e9. The exact conversion factor is
        // irrelevant — what matters is that we invert using the same internal extent span. But the
        // internal extent span is not carried alongside gps_bounds in the JSON; it is embedded in
        // the pts themselves. For placement accuracy, we approximate the internal extent by
        // computing meters-per-degree from gps_bounds with a WGS84 approximation.
        double lonSpanDeg = maxLon - minLon;
        double latSpanDeg = maxLat - minLat;
        if (lonSpanDeg <= 0 || latSpanDeg <= 0) {
            return new double[] {minLon, maxLat};
        }
        double midLat = (minLat + maxLat) / 2.0;
        double metersPerDegLat = 111_320.0;
        double metersPerDegLon = 111_320.0 * Math.cos(Math.toRadians(midLat));
        double xMeters = x / GEOM_SCALE;
        double yMeters = y / GEOM_SCALE;
        double lon = minLon + xMeters / metersPerDegLon;
        double lat = maxLat - yMeters / metersPerDegLat;
        // Clamp to bbox extents to avoid projection errors pushing nodes outside the canvas.
        lon = Math.max(minLon, Math.min(maxLon, lon));
        lat = Math.max(minLat, Math.min(maxLat, lat));
        return new double[] {lon, lat};
    }

    /** Helper for tests / callers that want to inspect the prefix constant. */
    static String idPrefix() {
        return ID_PREFIX;
    }

    /** Unused private — placeholder to satisfy potential reflection introspection. */
    @SuppressWarnings("unused")
    private static void touch(HashMap<String, String> ignored) {
        // intentionally empty
    }
}
