package com.trafficsimulator.controller;

import java.io.IOException;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import com.trafficsimulator.config.MapConfig;
import com.trafficsimulator.service.ClaudeVisionService;
import com.trafficsimulator.service.ClaudeVisionService.ClaudeCliException;
import com.trafficsimulator.service.ClaudeVisionService.ClaudeCliParseException;
import com.trafficsimulator.service.ClaudeVisionService.ClaudeCliTimeoutException;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

/** REST endpoint for AI vision-based map generation from uploaded road images. */
@RestController
@RequestMapping("/api/vision")
@RequiredArgsConstructor
@Slf4j
@CrossOrigin(origins = "*")
public class VisionController {

    private static final String ERROR_KEY = "error";
    private static final long MAX_FILE_SIZE = 10L * 1024 * 1024; // 10 MB

    private final ClaudeVisionService claudeVisionService;

    /**
     * Accepts a multipart image upload and returns a {@link MapConfig} generated by Claude CLI.
     *
     * @param image JPEG or PNG image of a road network
     * @return 200 MapConfig on success, or 400/422/503/504 on error
     */
    @PostMapping("/analyze")
    public ResponseEntity<?> analyzeImage(@RequestParam("image") MultipartFile image)
            throws IOException {

        if (image.isEmpty()) {
            return ResponseEntity.badRequest()
                    .body(Map.of(ERROR_KEY, "Image file must not be empty"));
        }

        String contentType = image.getContentType();
        if (contentType == null
                || (!contentType.equals("image/jpeg") && !contentType.equals("image/png"))) {
            return ResponseEntity.badRequest()
                    .body(Map.of(ERROR_KEY, "Only JPEG and PNG images are supported"));
        }

        if (image.getSize() > MAX_FILE_SIZE) {
            return ResponseEntity.badRequest()
                    .body(Map.of(ERROR_KEY, "Image must be under 10MB"));
        }

        log.info(
                "Vision analyze request: {} ({} bytes, {})",
                image.getOriginalFilename(),
                image.getSize(),
                contentType);

        MapConfig mapConfig = claudeVisionService.analyzeImage(image);
        return ResponseEntity.ok(mapConfig);
    }

    @ExceptionHandler(ClaudeCliTimeoutException.class)
    public ResponseEntity<Map<String, String>> handleTimeout(ClaudeCliTimeoutException e) {
        log.warn("Claude CLI timed out: {}", e.getMessage());
        return ResponseEntity.status(504)
                .body(Map.of(ERROR_KEY, "Analysis timed out. Please try again."));
    }

    @ExceptionHandler(ClaudeCliParseException.class)
    public ResponseEntity<Map<String, String>> handleParseError(ClaudeCliParseException e) {
        log.warn("Claude CLI parse error: {}", e.getMessage());
        return ResponseEntity.status(422)
                .body(Map.of(
                        ERROR_KEY,
                        "Could not parse road structure from image: " + e.getMessage()));
    }

    @ExceptionHandler(ClaudeCliException.class)
    public ResponseEntity<Map<String, String>> handleCliError(ClaudeCliException e) {
        log.error("Claude CLI unavailable: {}", e.getMessage());
        return ResponseEntity.status(503)
                .body(Map.of(
                        ERROR_KEY,
                        "Claude CLI is not available. Please use the OSM fetch path instead."));
    }

    @ExceptionHandler(IOException.class)
    public ResponseEntity<Map<String, String>> handleIoError(IOException e) {
        log.error("Image processing I/O error: {}", e.getMessage());
        return ResponseEntity.status(500)
                .body(Map.of(ERROR_KEY, "Failed to process uploaded image"));
    }
}
