package com.trafficsimulator.vision.components;

import java.util.ArrayList;
import java.util.List;

import com.trafficsimulator.config.MapConfig;
import com.trafficsimulator.config.MapConfig.DespawnPointConfig;
import com.trafficsimulator.config.MapConfig.IntersectionConfig;
import com.trafficsimulator.config.MapConfig.NodeConfig;
import com.trafficsimulator.config.MapConfig.RoadConfig;
import com.trafficsimulator.config.MapConfig.SpawnPointConfig;

/**
 * Mutable accumulator passed to {@link ComponentSpec#expand(ExpansionContext)}. Each component
 * appends to the public lists; {@link #toMapConfig(String, String)} assembles the final config.
 */
public final class ExpansionContext {

    /** Default spawn rate carried into the produced {@link MapConfig}. */
    public static final double DEFAULT_SPAWN_RATE = 0.6;

    public final List<NodeConfig> nodes = new ArrayList<>();
    public final List<RoadConfig> roads = new ArrayList<>();
    public final List<IntersectionConfig> intersections = new ArrayList<>();
    public final List<SpawnPointConfig> spawnPoints = new ArrayList<>();
    public final List<DespawnPointConfig> despawnPoints = new ArrayList<>();

    /**
     * Returns {@code componentId__localId}. The double underscore separator avoids collision with
     * the {@code _in}/{@code _out} suffix used by the engine routing convention.
     */
    public String prefix(String componentId, String localId) {
        return componentId + "__" + localId;
    }

    /** Convenience helper to build a {@link NodeConfig} record. */
    public NodeConfig addNode(String id, String type, double x, double y) {
        NodeConfig n = new NodeConfig();
        n.setId(id);
        n.setType(type);
        n.setX(x);
        n.setY(y);
        nodes.add(n);
        return n;
    }

    /** Convenience helper to build a {@link RoadConfig} record. */
    public RoadConfig addRoad(
            String id,
            String name,
            String fromNodeId,
            String toNodeId,
            double length,
            double speedLimit,
            int laneCount) {
        RoadConfig r = new RoadConfig();
        r.setId(id);
        r.setName(name);
        r.setFromNodeId(fromNodeId);
        r.setToNodeId(toNodeId);
        r.setLength(length);
        r.setSpeedLimit(speedLimit);
        r.setLaneCount(laneCount);
        roads.add(r);
        return r;
    }

    /** Convenience helper to build a {@link SpawnPointConfig}. */
    public SpawnPointConfig addSpawn(String roadId, int laneIndex, double position) {
        SpawnPointConfig sp = new SpawnPointConfig();
        sp.setRoadId(roadId);
        sp.setLaneIndex(laneIndex);
        sp.setPosition(position);
        spawnPoints.add(sp);
        return sp;
    }

    /** Convenience helper to build a {@link DespawnPointConfig}. */
    public DespawnPointConfig addDespawn(String roadId, int laneIndex, double position) {
        DespawnPointConfig dp = new DespawnPointConfig();
        dp.setRoadId(roadId);
        dp.setLaneIndex(laneIndex);
        dp.setPosition(position);
        despawnPoints.add(dp);
        return dp;
    }

    /** Builds a {@link MapConfig} from the accumulated state. */
    public MapConfig toMapConfig(String id, String name) {
        MapConfig cfg = new MapConfig();
        cfg.setId(id);
        cfg.setName(name);
        cfg.setDescription("Generated by MapComponentLibrary (Phase 21).");
        cfg.setNodes(new ArrayList<>(nodes));
        cfg.setRoads(new ArrayList<>(roads));
        cfg.setIntersections(new ArrayList<>(intersections));
        cfg.setSpawnPoints(new ArrayList<>(spawnPoints));
        cfg.setDespawnPoints(new ArrayList<>(despawnPoints));
        cfg.setDefaultSpawnRate(DEFAULT_SPAWN_RATE);
        return cfg;
    }
}
